import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopSide from "@/components/shared/TopSide";
import LeftSide from "@/components/shared/LeftSide";
import RightSide from "@/components/shared/RightSide";
import BottomSide from "@/components/shared/BottomSide";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <TopSide  />
<main className="flex flex-row">
    <LeftSide />
<div className="main-container">
    <section className="w-full max-w-4xl"> 
        {children}
    </section>
</div>
    <RightSide />
</main>
     <BottomSide />
        </body>
      </html>
    </ClerkProvider>
  );
}
